### PR TITLE
Remove escape:'html':'UTF-8'

### PR DESCRIPTION
**Pull request by MathiasReker**
Smarty’s strings are automatically escaped.

### CODE REVIEW

**Comment by MathiasReker** [comment]
@AllanWLie wdyt?

**Comment by MathiasReker** [comment]
documentation: http://build.prestashop.com/news/module-development-changes-in-17/

**Comment by AllanWLie** [comment]
@MathiasReker 
The reason you see old code is that the module must have support for Prestashop versions from 1.5 to 1.7

**Comment by MathiasReker** [comment]
Maybe the change should be done in only 1.7 templates then?

`epay/views/templates/front/paymenterror17.tpl`

`epay/views/templates/front/payment17.tpl`

In case of a template is used for both, you could add an if statement?

**Comment by MathiasReker** [comment]
Fixed and merged into https://github.com/ePay/prestashop/pull/33

**Pull request closed without merging**
